### ISSUE TITLE
Support testing hooks in isolation

### ISSUE THREAD

**Issue by CarsonMcKinstry** [testing-library/preact-testing-library#25]
- `preact-testing-library` version: any
- `preact` version: X
- `node` version: v12.13.1
- `npm` (or `yarn`) version: yarn - 1.22.4

Hi! My team got into the situation where we needed to test some preact hooks, and we were looking for a way to do this in isolation and we tried the `@testing-library/react-hooks` library. Due to the reliance on `react-test-renderer` the react hooks testing library will probably never be compatible with preact. 

With that being said, we decided to port the current `@testing-library/react-hooks` implementation to use preact, and we open sourced it on npm under `@trivago/preact-hooks-testing-library`.

**Github Repo**: https://github.com/trivago/preact-hooks-testing-library
**npm**: https://www.npmjs.com/package/@trivago/preact-hooks-testing-library

The big question at this point, is whether or not this library would be a good candidate to include under the `@testing-library` namespace?

**Comment by kentcdodds** [comment]
That's brilliant!

You're more than welcome to bring it in the testing library family both in GitHub and npm. Let me know if that's what you'd like to do and I'll give you access 👍

--- original message ---
On Fri, Jun 5 at 06:17 AM, <notifications@github.com> Carson McKinstry wrote:



preact-testing-library version: any

preact version: X

node version: v12.13.1

npm (or yarn) version: yarn - 1.22.4


Hi! My team got into the situation where we needed to test some preact hooks, and we were looking for a way to do this in isolation and we tried the @testing-library/react-hooks library. Due to the reliance on react-test-renderer the react hooks testing library will probably never be compatible with preact.

With that being said, we decided to port the current @testing-library/react-hooks implementation to use preact, and we open sourced it on npm under @trivago/preact-hooks-testing-library.

Github Repo: https://github.com/trivago/preact-hooks-testing-library

npm: https://www.npmjs.com/package/@trivago/preact-hooks-testing-library

The big question at this point, is whether or not this library would be a good candidate to include under the @testing-library namespace?

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Comment by kentcdodds** [comment]
I think there's value in having a separate package actually. Makes it easier for consumers.

**Comment by CarsonMcKinstry** [comment]
> That's brilliant! You're more than welcome to bring it in the testing library family both in GitHub and npm. Let me know if that's what you'd like to do and I'll give you access 👍

This would be great! Just let me know what all needs to happen from our side 😄

**Comment by kentcdodds** [comment]
Hi @CarsonMcKinstry,

I've just added you and the other two publishers to the npm and github org. Let me know what else you need.

**Comment by CarsonMcKinstry** [comment]
Oops! Forgot to update this issue! We moved the library and npm package over to the @testing-library/preact-hooks repo 😁  This issue can be safely closed.
